name: Deploy DevCenter Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Initialize Terraform
        working-directory: ./templates
        run: terraform init

      - name: Plan Terraform
        working-directory: ./templates
        run: terraform plan -var-file=../parameters/devcenter.tfvars

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main'
        working-directory: ./templates
        run: terraform apply -var-file=../parameters/devcenter.tfvars -auto-approve
