name: Deploy TFState Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Azure Powershell Script
      uses: azure/powershell@v2
      with:
        inlineScript: ./scripts/create_tfstate_container.ps1
        azPSVersion: "latest"

