name: Deploy TFState Container

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Azure Powershell Script
      uses: azure/powershell@v2
      with:
        inlineScript: ./scripts/create_tfstate_container.ps1
        azPSVersion: "latest"

